CREATE TABLE cities
(
    cities varchar(300)
);

INSERT INTO cities (cities) VALUES ('Chlef');
INSERT INTO cities (cities) VALUES ('Lagouat');
INSERT INTO cities (cities) VALUES ('Oum El Bouaghi');
INSERT INTO cities (cities) VALUES ('Batna');
INSERT INTO cities (cities) VALUES ('Béjaia');
INSERT INTO cities (cities) VALUES ('Biskra');
INSERT INTO cities (cities) VALUES ('Béchar');
INSERT INTO cities (cities) VALUES ('Blida');
INSERT INTO cities (cities) VALUES ('Bouira');
INSERT INTO cities (cities) VALUES ('Tamanrasset');
INSERT INTO cities (cities) VALUES ('Tébessa');
INSERT INTO cities (cities) VALUES ('Tlemcen');
INSERT INTO cities (cities) VALUES ('Tiaret');
INSERT INTO cities (cities) VALUES ('Tizi Ouzou');
INSERT INTO cities (cities) VALUES ('Alger');
INSERT INTO cities (cities) VALUES ('Djelfa');
INSERT INTO cities (cities) VALUES ('Jijel');
INSERT INTO cities (cities) VALUES ('Setif');
INSERT INTO cities (cities) VALUES ('Saida');
INSERT INTO cities (cities) VALUES ('Skikda');
INSERT INTO cities (cities) VALUES ('Sidi Bel Abbès');
INSERT INTO cities (cities) VALUES ('Annaba');
INSERT INTO cities (cities) VALUES ('Guelma');
INSERT INTO cities (cities) VALUES ('Constantine');
INSERT INTO cities (cities) VALUES ('Médéa');
INSERT INTO cities (cities) VALUES ('Mostaganem');
INSERT INTO cities (cities) VALUES ('M'silla');
INSERT INTO cities (cities) VALUES ('Mascara');
INSERT INTO cities (cities) VALUES ('Ouargla');
INSERT INTO cities (cities) VALUES ('Oran');
INSERT INTO cities (cities) VALUES ('El Bayadh');
INSERT INTO cities (cities) VALUES ('Illizi');
INSERT INTO cities (cities) VALUES ('Bordj Bou Arreridj');
INSERT INTO cities (cities) VALUES ('Boumerdes');
INSERT INTO cities (cities) VALUES ('El Tarf');
INSERT INTO cities (cities) VALUES ('Tindouf');
INSERT INTO cities (cities) VALUES ('Tissemsilet');
INSERT INTO cities (cities) VALUES ('El Oued');
INSERT INTO cities (cities) VALUES ('Khenchela');
INSERT INTO cities (cities) VALUES ('Souk Ahras');
INSERT INTO cities (cities) VALUES ('Tipaza');
INSERT INTO cities (cities) VALUES ('Milla');
INSERT INTO cities (cities) VALUES ('Ain Defla');
INSERT INTO cities (cities) VALUES ('Naama');
INSERT INTO cities (cities) VALUES ('Timouchent');
INSERT INTO cities (cities) VALUES ('Ghardaia');
INSERT INTO cities (cities) VALUES ('Ghilizane');
INSERT INTO cities (cities) VALUES ('Timimoun');
INSERT INTO cities (cities) VALUES ('Bordj Badji Mokhtar');
INSERT INTO cities (cities) VALUES ('Ouled Djalal');
INSERT INTO cities (cities) VALUES ('Béni Abbas');
INSERT INTO cities (cities) VALUES ('In Salah');
INSERT INTO cities (cities) VALUES ('In Gazzam');
INSERT INTO cities (cities) VALUES ('Touggourt');
INSERT INTO cities (cities) VALUES ('Djanet');
INSERT INTO cities (cities) VALUES ('M'Ghairr');
INSERT INTO cities (cities) VALUES ('Méniaa');
