array(
   "Adrar",
   "Chlef",
   "Lagouat",
   "Oum El Bouaghi",
   "Batna",
   "Béjaia",
   "Biskra",
   "Béchar",
   "Blida",
   "Bouira",
   "Tamanrasset",
   "Tébessa",
   "Tlemcen",
   "Tiaret",
   "Tizi Ouzou",
   "Alger",
   "Djelfa",
   "Jijel",
   "Setif",
   "Saida",
   "Skikda",
   "Sidi Bel Abbès",
   "Annaba",
   "Guelma",
   "Constantine",
   "Médéa",
   "Mostaganem",
   "M'silla",
   "Mascara",
   "Ouargla",
   "Oran",
   "El Bayadh",
   "Illizi",
   "Bordj Bou Arreridj",
   "Boumerdes",
   "El Tarf",
   "Tindouf",
   "Tissemsilet",
   "El Oued",
   "Khenchela",
   "Souk Ahras",
   "Tipaza",
   "Milla",
   "Ain Defla",
   "Naama",
   "Timouchent",
   "Ghardaia",
   "Ghilizane",
   "Timimoun",
   "Bordj Badji Mokhtar",
   "Ouled Djalal",
   "Béni Abbas",
   "In Salah",
   "In Gazzam",
   "Touggourt",
   "Djanet",
   "M'Ghairr",
   "Méniaa");
